# Generated by Django 4.2 on 2023-04-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='valuta',
            field=models.CharField(default=12, max_length=4),
            preserve_default=False,
        ),
    ]
