# Generated by Django 4.2 on 2023-04-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPopular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('img_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
    ]
