# Generated by Django 4.2 on 2023-04-10 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_image_productpopular_remove_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpopular',
            name='img_id',
        ),
        migrations.RemoveField(
            model_name='productpopular',
            name='product_id',
        ),
        migrations.AddField(
            model_name='productpopular',
            name='img',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpopular',
            name='product',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BestSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
