# Generated by Django 4.2 on 2023-04-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_startbanners_offerbanners'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurContactsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=35)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
